# Generated by Django 5.2.7 on 2025-10-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
